GETTING DATA

In [1]:
import numpy as np

In [2]:
data = np.load("./data.npz")
X_train = data["X_train"]
Y_train = data["Y_train"]
X_test = data["X_test"]
print("Shapes")
print("X_train:",X_train.shape)
print("Y_train:",Y_train.shape)
print("X_test:",X_test.shape)

Shapes
X_train: (10714, 21)
Y_train: (10714,)
X_test: (14498, 21)


COMPILING KERAS MODEL

In [8]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential

In [9]:
model = Sequential()
model.add(Dense(32, input_dim=21, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="relu"))
model.add(Dense(64, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="relu"))
model.add(Dense(32, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="relu"))
model.add(Dense(1, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="sigmoid"))

In [10]:
model.compile(loss="mean_squared_error", optimizer="adam")

TRAINING MODEL

In [11]:
labels = Y_train.reshape(-1,1)
epochs = 10
labels

array([[0.49135008],
       [0.5114788 ],
       [0.73223996],
       ...,
       [0.47708535],
       [0.53803563],
       [0.683424  ]], dtype=float32)

In [12]:
model.fit(X_train,Y_train.reshape(-1,1), validation_split=0.1, epochs=epochs)

Train on 9642 samples, validate on 1072 samples
Epoch 1/10
9642/9642 [==============================] - 1s 93us/sample - loss: 0.0090 - val_loss: 0.0097
Epoch 2/10
9642/9642 [==============================] - 1s 59us/sample - loss: 0.0080 - val_loss: 0.0096
Epoch 3/10
9642/9642 [==============================] - 1s 58us/sample - loss: 0.0079 - val_loss: 0.0095
Epoch 4/10
9642/9642 [==============================] - 1s 53us/sample - loss: 0.0078 - val_loss: 0.0094
Epoch 5/10
9642/9642 [==============================] - 0s 51us/sample - loss: 0.0077 - val_loss: 0.0096
Epoch 6/10
9642/9642 [==============================] - 1s 52us/sample - loss: 0.0077 - val_loss: 0.0093
Epoch 7/10
9642/9642 [==============================] - 1s 52us/sample - loss: 0.0076 - val_loss: 0.0094
Epoch 8/10
9642/9642 [==============================] - 0s 52us/sample - loss: 0.0076 - val_loss: 0.0090
Epoch 9/10
9642/9642 [==============================] - 1s 52us/sample - loss: 0.0075 - val_loss: 0.0090
Epoch 1

In [14]:
y_pred = model.predict(X_train)

In [16]:
y_pred

array([[0.48578078],
       [0.50200367],
       [0.6030181 ],
       ...,
       [0.5008443 ],
       [0.5318643 ],
       [0.65179557]], dtype=float32)

In [17]:
labels

array([[0.49135008],
       [0.5114788 ],
       [0.73223996],
       ...,
       [0.47708535],
       [0.53803563],
       [0.683424  ]], dtype=float32)

In [13]:
model.save("model.h5")