GETTING DATA

In [1]:
import numpy as np

In [2]:
data = np.load("./data.npz")
X_train = data["X_train"]
Y_train = data["Y_train"]
X_test = data["X_test"]
print("Shapes")
print("X_train:",X_train.shape)
print("Y_train:",Y_train.shape)
print("X_test:",X_test.shape)

Shapes
X_train: (10714, 21)
Y_train: (10714,)
X_test: (14498, 21)


COMPILING KERAS MODEL

In [3]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential

In [4]:
model = Sequential()
model.add(Dense(32, input_dim=21, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="relu"))
model.add(Dense(64, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="relu"))
model.add(Dense(32, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="relu"))
model.add(Dense(1, kernel_initializer='glorot_uniform',
                bias_initializer='zeros', activation="sigmoid"))

In [5]:
model.compile(loss="mean_squared_error", optimizer="adam")

TRAINING MODEL

In [6]:
labels = Y_train.reshape(-1,1)
epochs = 10
labels

array([[0.4913501 ],
       [0.5114788 ],
       [0.73224   ],
       ...,
       [0.47708533],
       [0.53803565],
       [0.683424  ]])

In [7]:
model.fit(X_train,Y_train.reshape(-1,1), validation_split=0.1, epochs=epochs)

Train on 9642 samples, validate on 1072 samples
Epoch 1/10
9642/9642 [==============================] - 1s 99us/sample - loss: 0.0085 - val_loss: 0.0107
Epoch 2/10
9642/9642 [==============================] - 1s 53us/sample - loss: 0.0080 - val_loss: 0.0094
Epoch 3/10
9642/9642 [==============================] - 1s 53us/sample - loss: 0.0079 - val_loss: 0.0094
Epoch 4/10
9642/9642 [==============================] - 1s 53us/sample - loss: 0.0078 - val_loss: 0.0095
Epoch 5/10
9642/9642 [==============================] - 1s 52us/sample - loss: 0.0077 - val_loss: 0.0093
Epoch 6/10
9642/9642 [==============================] - 1s 52us/sample - loss: 0.0076 - val_loss: 0.0093
Epoch 7/10
9642/9642 [==============================] - 1s 52us/sample - loss: 0.0075 - val_loss: 0.0093
Epoch 8/10
9642/9642 [==============================] - 1s 53us/sample - loss: 0.0075 - val_loss: 0.0101
Epoch 9/10
9642/9642 [==============================] - 1s 53us/sample - loss: 0.0075 - val_loss: 0.0096
Epoch 1

In [8]:
y_pred = model.predict(X_train)

In [9]:
y_pred

array([[0.4874287 ],
       [0.5188278 ],
       [0.5795431 ],
       ...,
       [0.48518467],
       [0.5356131 ],
       [0.6211264 ]], dtype=float32)

In [10]:
labels

array([[0.4913501 ],
       [0.5114788 ],
       [0.73224   ],
       ...,
       [0.47708533],
       [0.53803565],
       [0.683424  ]])

In [11]:
model.save("model.h5")